name: pos
description: "POS demo application for FIN Infocom"
publish_to: 'none'
version: 0.0.1+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter

  # State Management
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3

  # Local Storage
  path_provider: ^2.1.1
  sqflite: ^2.3.0

  # Utilities
  google_fonts: ^6.1.0
  intl: ^0.19.0
  path: ^1.8.3
  uuid: ^4.2.1

  # UI
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
